# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2015, Spring'
tagline:          'A workshop for GAP developers and users'
description:      'March 16-20, 2015'
location:         'RWTH Aachen University'
url:              http://gapdays.coxeter.de/
baseurl:          /


exclude: [ "program.aux", "program.log", "program.out", "program.tex", "misc" ]
include: [ "gapday2015-program.pdf" ]
