# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days 2015, Spring'
tagline:          'A workshop for GAP developers and users'
#description:      'A workshop for <a href="http://www.gap-system.org/">GAP</a> developers and users.'
#description:      'A workshop for <a href="http://www.gap-system.org/">GAP</a> developers and users, August 25-29, 2014, RWTH Aachen University.'
description:      'March 16-20, 2015'
url:              http://gapdays.coxeter.de/
baseurl:          /


exclude: [ "gapday2015-program.*", "misc" ]
include: [ "gapday2015-program.pdf" ]
